sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-017
env:
  global:
    -
      # LTD_AWS_ID
      secure: yOxcOOu+nJFjvoU6yOw98B6jRuv+LaRHmQOfwQmbMkS7GP0dOYJJM8zrjfV+uyrgbB6jw82sWtMVp/4q+zh4w0tBzw7LGlezprwU8EZQgYnBys5byTB3khVcLBjEidNehwdJ0Rfgj5l8zJ/RxD0UV+jZnWL3uiC6NWhc6aIyvMFIEXpR10A8XQyu9/UndMJAHVK8hyDGUNbcVvXbJc3kjKSc4Z2svxuA48xR4OS76zMmr8fBhrAaWRKNvsbOvxXeXk04e5lVQ4L7Z7wqZblgiISkp5JxbZspkjS5k6K4IWbjbfraAFZZdeEq0UzE+1CFidlVbo6EaVW82GVIEf6Bn+Zn0O/WiJisjsvq4Hy2IFXJemZK0wDhrIgrMzHP31EoQYvyoEZ9mRm3GMw4Msh2MMALF7MshBxL8f9hiXJPKmNWQHVKeEEpjJ60laUnfNJb14lmmxflyFbcJ9gR73pbebj78h6iso/livF9oM7LasqC/EsbqGd6ir3a+ZJlij6ROphbNmtH/pwoZBBSI+VVBUTouK0IO8g8ThVeLhcIIViZwMokgLE6DC7iAAn3gvH88Dq7CLsfjFOPBlmRHerfpr8CSb4Y02C/xttS2FmBadx+ZGj+4os+a8NRqI2Z9YnRJLcE9RU1+XTI1AUSG2uVBg00Z9pzGhaw7Int9y1O9kE=
    -
      # LTD_AWS_SECRET
      secure: q5NBpjqDSZWB5Mgnv8LJ0sn5so/e6du0HU4Qj6QXbpmuu8thn7vPYmsLbwDscMgoulY4rmGyAp0v7pIHTxFlSpuYxizG+Wv8ipZgf9/gBfgX0LUyxdM9dVgjMRMjyslfdP5tys3cEEE1v2Y7nlN4hZfRP/SUEpdsIiPUAKf4v7hsqcF+UAV8jULHNqZ2OAHLi5oihVl/Q1PUgBnSQenE7kpW4qYRXCmsA2zMmojn3WdxLpyKmVXMWDrTfImMK9hmF+9lf3AFh6o7/Kc1/v+E36hcBjJQJdAZ/meeoqHWP2pn/GqguZpnI9TmujKCVlUGLYmUpiViAq1GLbMzfpTct+Xm5ggq/tQBAtZsXkcCxeKz1zan29gAKymLn7nNK5rzVhJQIvT/kvJdv+lM5X/0hm3fpV8MnMP2PE6Spy5nyhcIuqPDkn/Q2kK/VRnZGGA0RqQoH1KeRa12VnQC565l8DwSljfZH7yyk5N1smLEbeMSDA0lQqFesedABjkVFx1oxz2o2sZVf0vk7tkd9Madg+mmt9cqbBdj/33fWhtnPohWUgBFHsumoBlhE9piszAfHpnEDloYM+6z2Ab6pryHs1jtRCRaQStfkPIaobYk9Q14vipaXmN5iEzYzrwWyahtUBA5fMwlzNSuveVbSbE7YuoGPddzC27BhhEGkn9evHU=
    -
      # LTD_USERNAME
      secure: eLIiBJu2AOVHdVKqvPv58n8YOdGcdRPnXW7wtuwvABbNKhXT0PJO+5BUg020tyRepnwzo+CVawkXHhhnP1e1T8s9sMy8OyXeojt92GOhbgc/QD0Z0p3KlsWsu6i55LE5F4tC8hTLBMo3Ezhq9MWpv7R33wwjO5Mc7RGiYKu2bNdnoUyTKBYggPQNRGtBdu14N4XsncwS8ebnXcsoe8Kpnmk8tU8Dqt6x+ZVDzqZ7sg/1ESc2T2ErmPFsXj8K9GKHMlOT2LggXYopkAvDNrgG+0oxxtUvLf+uSYtrGJr0Bv8eOgds2ivVi7I4B/IgjbzR6F8Vn7Mpn6gJyLC90/bMTEN6KMeU5DwsC+/++AEOGEmKu2J5/6Xi5/0HiXPMHDHq6ngTScY5ayWM2idmLp+ZnPt1B0anOu9TmPlRy1wU95cTfjTn1fqcJxCusa0YbaMQLwbBL10/xNjjKkpkRpMW5JcmzGF/8unEWn6EYaFy6qQTHoVdr1iXTBUjQr36S5MTp2MVZh9hN/7RKiQXTsVlfcVnKUJVLUOOEoCoqjEv8muNHbFWjPD0rX1VJ/vPyteRdXiurb/Av334gzUKbVu2SSjKWY1SPfIHjFMWtAoLt+ggIdSecJkwcGq3NZrQZBz7yQ1mGHzCAogVEKxbGzhDeHZok+1K55hMYvTVDdhQyVg=
    -
      # LTD_PASSWORD
      secure: Cj67MTVj9QAMhevueCu7dImqSdff5xht3TBKzZffWN+I3wP2WEj8cSNrbwCPM26F2LH+HiG71u7xp2KjbIZ6btvEtcqfVjNEDIgtsIcGLUFS+XeGMpuhJ2D7ZVS2P9VpHt1e1QxdLC+Pd9qu+mOc0YcxN6PRTODM6Yp90i84rJJ5+q7vGL3onreqgtqvf1UOWoJrIqp4BNzxsZZ0B1DncIocOVFej5/P1ElNd7LioD8tzG06YpRyqspTQhSQqFoRW3qyy3xHnaqqYjaxTP0BCOEA/RvugdSY1XjMfallnFCYnHHZ6j1B1Bu3TCO7PFW/SYsnkV6S0bN0+dXuVufhX5l04XcFA9anLTUMRp10JjvzwaqsscIZ/P0mQX40ufW3jvEtBrT9mMW49LQciToCVC1pN3al3By3jFuZdNEwqmRQWWB8k5SxvWLUU3iyv5glN6U+meFTtinm9JY6tu4VwE7uvlFF4+wOuUL+ULjgST6ynMqMrqugRqFzx0XIsA6To7RG1Iy+Vp0HOdC09//QFbxph+Fvbq7h61icLB98Km0yXg3F086WTjNfL/UXF4WdX3MpPELF5Oe7P8kjsZcWk7Sx5+Haoe5YxwdXCTGdW/Rs5J/6qjm/4c4N1PeZakyfQjq8ocPtetWWccMXtrOhUb99SI/OlHHIDcjnC8RWTuI=
